### ISSUE TITLE
Backend Stack Discussion

### ISSUE THREAD

**Issue by jmartin84** [cohesivelabs/glue#1]

**Comment by CWSpear** [comment]
So we're definitely at a place where I'd like to be latest Node `4.x` if possible, and we should try and support the latest `Docker` and all that, too.

**Comment by jmartin84** [comment]
I agree.

What about framework, we could just do plain old express but I wouldn't mind finding something a little more polished thats connect friendly.

**Comment by jmartin84** [comment]
that being said, I've never been super impressed with sails.

**Comment by CWSpear** [comment]
So I mentioned it in the frontend, but I want to give something that does the 3-way binding stuff a try, e.g. LookBack. I mentioned it in the frontend side since it is isomorphic, but most of what we'd be doing really is the front, and it'd handle most of our persistence and auth on the backend somewhat out of the box.

**Comment by CWSpear** [comment]
The lines are _blurred_. We don't need two threads anymore. It's all JavaScript, all the places!

**Comment by jmartin84** [comment]
closed in favor of https://github.com/cohesivelabs/glue/issues/2
